language: cpp

git:
  depth: 1
  submodules: false
  
env:
  global:
    - BUILD_FILENAME="build-$TRAVIS_OS_NAME.$TRAVIS_BUILD_NUMBER-$(date '+%Y-%m-%d_%H_%M_%S').tgz"
    - MAKE_THREADS=4

matrix:
  include:
  
  - os: linux
    name: "Synfig Studio Ubuntu 16.04 Xenial (GCC/Autotools)"
    sudo: required
    dist: xenial
    cache: ccache
    before_install: autobuild/install-requirements-linux.sh
    before_script: ccache -s
    script: autobuild/synfigstudio-linux-build.sh
    after_install: autobuild/synfigrenderer-regression-test.sh
    after_script: ccache -s # show ccache stats
        
  - os: osx
    name: "Synfig Studio OS X 10.10 Yosemite (Clang/Autotools/Brew)"
    sudo: required
    osx_image: xcode6.4
    env:
      - HOMEBREW_NO_AUTO_UPDATE=1
      - HOMEBREW_NO_ANALYTICS=1
    cache: ccache
    before_install: brew reinstall libtool # fix no sed
    install: autobuild/osx/brew/install-requirements-osx.sh
    before_script: ccache -s
    script: autobuild/osx/brew/synfigstudio-osx-build.sh
    after_script: ccache -s # show ccache stats
    
  - os: osx
    name: "Synfig Studio OS X 10.13 High Sierra (Clang/Autotools/Brew)"
    sudo: required
    osx_image: xcode10
    env:
      - HOMEBREW_NO_AUTO_UPDATE=1
      - HOMEBREW_NO_ANALYTICS=1
    cache: ccache
    before_install: brew cask uninstall oclint # fix gcc installing
    install: autobuild/osx/brew/install-requirements-osx.sh
    before_script:
      - ccache -s
      - ccache --set-config=compression=true
    script: autobuild/osx/brew/synfigstudio-osx-build.sh
    after_script: ccache -s # show ccache stats
    
  #allow_failures:
  #  - os: osx
